### ISSUE TITLE
Caused by: java.io.IOException: Unable to locate model [english.par] 

### ISSUE THREAD

**Issue by stephane54** [termsuite/termsuite-docker#1]
Bonjour,
Avec la version 3.2.1 à 3.2.2 du treetagger, termsuite 3.0.10 semble avoir des soucis pour charger les ressources du tagger.
Même après avoir changés les noms des fichiers de paramètres comme ci dessous :
RUN wget ${TT_URL}/tree-tagger-linux-${TT_VERSION}.tar.gz \
    && wget ${TT_URL}/tagger-scripts.tar.gz \
    && wget ${TT_URL}/english.par.gz \
    && wget ${TT_URL}/french.par.gz \
    && wget ${TT_URL}/german.par.gz \
    && wget ${TT_URL}/russian.par.gz \
    && wget ${TT_URL}/italian.par.gz \
    && wget ${TT_URL}/spanish.par.gz \
    && wget ${TT_URL}/install-tagger.sh \
    && sh /opt/treetagger/install-tagger.sh \
    && mv lib models \
    && rm -rf *.gz *.tgz cmd/ doc/

Les fichiers sont apparemment bien disponibles à cet endroit dans le conteneur.

Exemple de commande :
bin/termsuite extract --tsv my-termino.tsv -c  /applis/termsuite/home/data/in/English/txt -l en -t /opt/treetagger/bin

TRACE ============================================
Starting with UID : 1106
Found arg -c. Adding option -t /opt/treetagger
Executing: java -cp /opt/termsuite-core-3.0.10.jar fr.univnantes.termsuite.tools.TerminologyExtractorCLI -t /opt/treetagger --tsv my-termino.tsv -c /applis/termsuite/home/data/in/English/txt -l en -t /opt/treetagger/bin
Exception in thread "main" fr.univnantes.termsuite.tools.TermSuiteCliException: An unexpected error occurred: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "fr.univnantes.lina.uima.engines.TreeTaggerWrapper" failed.  (Descriptor: <unknown>)
        at fr.univnantes.termsuite.tools.CommandLineClient.launch(CommandLineClient.java:295)
        at fr.univnantes.termsuite.tools.TerminologyExtractorCLI.main(TerminologyExtractorCLI.java:203)
Caused by: fr.univnantes.termsuite.api.TermSuiteException: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "fr.univnantes.lina.uima.engines.TreeTaggerWrapper" failed.  (Descriptor: <unknown>)
        at fr.univnantes.termsuite.api.Preprocessor.asService(Preprocessor.java:334)
        at fr.univnantes.termsuite.api.Preprocessor.asService(Preprocessor.java:284)
        at fr.univnantes.termsuite.api.Preprocessor.toIndexedCorpus(Preprocessor.java:124)
        at fr.univnantes.termsuite.tools.TerminologyExtractorCLI.getIndexedCorpus(TerminologyExtractorCLI.java:192)
        at fr.univnantes.termsuite.tools.TerminologyExtractorCLI.run(TerminologyExtractorCLI.java:136)
        at fr.univnantes.termsuite.tools.CommandLineClient.launch(CommandLineClient.java:287)
        ... 1 more
Caused by: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "fr.univnantes.lina.uima.engines.TreeTaggerWrapper" failed.  (Descriptor: <unknown>)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:272)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:172)
        at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
        at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
        at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
        at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:435)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:379)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:192)
        at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
        at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
        at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
        at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:435)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:379)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:192)
        at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
        at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
        at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
        at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:435)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:379)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:192)
        at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
        at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
        at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
        at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:331)
        at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:448)
        at fr.univnantes.termsuite.api.Preprocessor.asService(Preprocessor.java:332)
        ... 6 more
Caused by: org.apache.uima.resource.ResourceInitializationException
        at fr.univnantes.lina.uima.engines.TreeTaggerWrapper.initialize(TreeTaggerWrapper.java:157)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:267)
        ... 37 more
Caused by: java.io.IOException: Unable to locate model [english.par] in the following locations [/opt/treetagger/models/english.par].  Make sure the environment variable 'TREETAGGER_HOME' or 'TAGDIR' or the system property 'treetagger.home' point to the TreeTagger installation directory.
        at org.annolab.tt4j.DefaultModelResolver.getModel(DefaultModelResolver.java:126)
        at org.annolab.tt4j.DefaultModelResolver.getModel(DefaultModelResolver.java:97)
        at org.annolab.tt4j.TreeTaggerWrapper.setModel(TreeTaggerWrapper.java:471)
        at fr.univnantes.lina.uima.engines.TreeTaggerWrapper.initialize(TreeTaggerWrapper.java:146)

Stéphane S 
INIST-CNRS Nancy

**Comment by mhabsaoui** [comment]
Bonjour @stephane54,

> Exemple de commande :
bin/termsuite extract --tsv my-termino.tsv -c /applis/termsuite/home/data/in/English/txt -l en **-t /opt/treetagger/bin**

A priori pas de besoin de passer le paramètre de chemin du treetagger dans la commande, pour la version Docker de Termsuite.

Je n'ai pas d'exception générée sur mon environnent:

- Il a effectivement fallu corriger le Dockerfile (URLs des ressources pour le TreeTagger) => Voir modifs sur ma [Pull-Request](https://github.com/termsuite/termsuite-docker/pull/2/files) soumise.
L'image est build correctement.

- L'extraction lancee se deroule sans erreur, avec la commande : 
`bin/termsuite extract --tsv `pwd`/my-termino.tsv -c ~/Documents/wind-energy/English/txt -l en`
`Starting with UID : 1000`
`Found arg -c. Adding option -t /opt/treetagger`
`Executing: java -cp /opt/termsuite-core-3.0.10.jar fr.univnantes.termsuite.tools.TerminologyExtractorCLI -t /opt/treetagger --tsv /home/user/Documents/termsuite-docker/my-termino.tsv -c /home/user/Documents/wind-energy/English/txt -l en`

J'ai bien mon fichier `my-termino.tsv` correctement généré.

J'ai pu aussi y arriver directement avec une commande docker (sans faire appel au script  dans bin/termsuite) a l'aide de la commande suivante: 

```
docker run --rm -v "${HOME}:${HOME}" -e LOCAL_USER_ID=`id -u $USER` termsuite:3.0.10 extract --json `pwd`/my-termino.json -c ~/Documents/wind-energy/English/txt -l en
```
